# Generated by Django 3.2 on 2021-05-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20210508_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=10.99),
        ),
    ]
