# Generated by Django 3.2 on 2021-05-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_item_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
